name: Create release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      REPO_NAME: ${{ github.event.repository.name }}
    steps:
      - uses: actions/checkout@v2
        with:
          node-version: 16
          cache: "yarn"

      - name: Set up node
        uses: actions/setup-node@v2
        with:
          always-auth: true
          node-version: 16
          registry-url: 'https://npm.pkg.github.com'
          scope: '@transformd-ltd'

      - name: Install yarn packages
        run: yarn install --frozen-lockfile
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PUBLIC_NPM_TOKEN }}

      - name: Get Tag
        id: get_tag
        run: echo ::set-output name=tag::$(echo $GITHUB_REF | cut -d / -f 3)

      - name: Build
        run: yarn package

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/app.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
